# Site settings
baseurl = "http://josdem.io/"
languageCode = "en-us"
title = "josdem"
theme = "hugo-artists-theme"
disqusShortname = "josdem"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Jose Luis De la Cruz Morales"
	description = "Software Developer"

	# Since this template is static, the contact form uses www.formspree.io as a
	# proxy. The form makes a POST request to their servers to send the actual
	# email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
	email = "contact@josdem.io"


	# Header an navigation
	#
	# To change the header background the 'hero-bg-jpg' at 'static/img'.
	# Do the same with the logo ('logo.svg').
	# But keep the original filename!
	[params.header]
		title = "josdem"
		shortBio = "Developer // Agile // DJ"


	# About section
	#
	# Replace the 'avatar.jpg' under 'static/img' with your own image.
	[params.about]
		title = "About me"
		bio = "**Jose Luis is a software developer** eager to contribute in products. He has four public projects [Jmetadata](/jmetadata/jmetadata), [Jugoterapia](/jugoterapia/jugoterapia), [Jmailer](http://jmailer.josdem.io/) and [Vetlog](http://vetlog.org/), he enjoy to write about technology so he has a [Techtalks](/techtalk/techtalks) section, his hobby is creating [Mixes](/music/myremixes) because he thinks that sharing is caring."

		[[params.about.skills]]
			name = "Communication"
			value = 8

		[[params.about.skills]]
			name = "Organization"
			value = 8

		[[params.about.skills]]
			name = "Learning"
			value = 10

		[[params.about.skills]]
			name = "Teaching"
			value = 9
		[[params.about.skills]]
			name = "Planning"
			value = 8

		[[params.about.skills]]
			name = "UX Developer"
			value = 6

		[[params.about.skills]]
			name = "Backend developer"
			value = 9

		[[params.about.skills]]
			name = "Programming"
			value = 9

	# Work section
	[params.work]
		title = "Techtalks"

		[[params.work.projects]]
			name = "Groovy"
			folder = "proj-1"

		[[params.work.projects]]
			name = "C++"
			folder = "proj-2"

		[[params.work.projects]]
			name = "Spring"
			folder = "proj-3"

		[[params.work.projects]]
			name = "Elixir"
			folder = "proj-4"

		[[params.work.projects]]
			name = "UX Design"
			folder = "proj-5"

		[[params.work.projects]]
			name = "Sysadmin"
			folder = "proj-6"

		[[params.work.projects]]
			name = "Algorithms"
			folder = "proj-7"

		[[params.work.projects]]
			name = "Java"
			folder = "proj-8"


	# Clients section
	[params.clients]
		title = "Contacts"

		[[params.clients.list]]
			avatar = "theo.jpg"
			name   = "Theo Grip"
			title  = "Software Developer, 1&1 Internet AG"
			quote  = "**José Luis fue un compañero muy trabajador.** Siempre se interesó por las nuevas tecnologías y estuvo aprendiendo nuevas cosas. Tiene mucha ambición y trabaja rápido. Siempre esta dispuesto a ayudar y fue un placer hacer pair programming con él."
			logo   = "1and1.png"

		[[params.clients.list]]
			avatar = "felipe.jpg"
			name   = "Felipe Juarez"
			title  = "Software Developer, Makingdevs."
			quote  = "**José Luis un gran desarrollador, compañero, mentor y mejor amigo.** Interesado por conocer sobre tecnologías, mejores prácticas y compartir cada uno de sus descubrimientos. Apasionado del TDD, la música electrónica, las chelas, el mezcal y de entablar buenas conversaciones."
			logo   = "makingdevs.png"

		[[params.clients.list]]
			avatar = "temoc.png"
			name   = "Cuauhtémoc Palma"
			title  = "Software Developer, TIM"
			quote  = "**Gran amigo, excelente compañero de trabajo y desarrollador de software profesional.** Además conocedor de la historia de méxico y universal, de la buena comida, y entusiasta del mezcal."
			logo   = "techminds.png"

		[[params.clients.list]]
			avatar = "face-teleject.jpg"
			name   = "Cleatus Cassidy"
			title  = "VP of Helmut, Lorem Sorem LLC."
			quote  = "**Back in old country** only nerds who is playing on computers. Now all bros is wanting to make codes and junk. I lost foot in war. You dont see girls asking me about homework."
			logo   = "logo4.png"


	# Contact secion
	[params.contact]
		title = "Contact"

		# The following social network icons are available:
		# 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin'
		# 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
		#
		[[params.contact.social]]
			icon = "github"
			link = "//github.com/josdem"

    [[params.contact.social]]
			icon = "twitter"
			link = "//twitter.com/josdem"


		[[params.contact.social]]
			icon = "behance"
			link = "//mixcloud.com/josdem"

		[[params.contact.social]]
			icon = "instagram"
			link = "//instagram.com/j0sdem"

		[[params.contact.social]]
			icon = "linkedin"
			link = "//linkedin.com/pub/jose-luis-de-la-cruz-morales/9/11a/5b9"


	[params.form]
		title = "Let's do stuff together"
		# Form fields
		service = "//jmailer.josdem.io/emailer/form"
    source = "josdem.io"
    template = "third_party.ftl"
		name = "Your Name"
		email = "Your Email"
		message = "Send me some message"
    redirect = "http://josdem.io/flyer/jmailer/"
    destination = "joseluis.delacruz@gmail.com"
		buttonText = "Send"


	[params.footer]
		copyright = "Published under the Unlicense License."
